// <auto-generated />
using System;
using Frank.Apps.StarMap.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Frank.Apps.StarMap.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Frank.Apps.StarMap.Models.Star", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Absmag")
                        .HasColumnType("REAL");

                    b.Property<string>("Base")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bayer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ci")
                        .HasColumnType("TEXT");

                    b.Property<int>("Comp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Con")
                        .HasColumnType("TEXT");

                    b.Property<double>("Dec")
                        .HasColumnType("REAL");

                    b.Property<double>("Decrad")
                        .HasColumnType("REAL");

                    b.Property<double>("Dist")
                        .HasColumnType("REAL");

                    b.Property<int?>("Flam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Hd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Hip")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Hr")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Lum")
                        .HasColumnType("REAL");

                    b.Property<string>("Mag")
                        .HasColumnType("TEXT");

                    b.Property<double>("Pmdec")
                        .HasColumnType("REAL");

                    b.Property<double>("Pmdecrad")
                        .HasColumnType("REAL");

                    b.Property<double>("Pmra")
                        .HasColumnType("REAL");

                    b.Property<double>("Pmrarad")
                        .HasColumnType("REAL");

                    b.Property<string>("Proper")
                        .HasColumnType("TEXT");

                    b.Property<double>("Ra")
                        .HasColumnType("REAL");

                    b.Property<double>("Rarad")
                        .HasColumnType("REAL");

                    b.Property<double>("Rv")
                        .HasColumnType("REAL");

                    b.Property<string>("Spect")
                        .HasColumnType("TEXT");

                    b.Property<string>("Var")
                        .HasColumnType("TEXT");

                    b.Property<string>("VarMax")
                        .HasColumnType("TEXT");

                    b.Property<string>("VarMin")
                        .HasColumnType("TEXT");

                    b.Property<double>("Vx")
                        .HasColumnType("REAL");

                    b.Property<double>("Vy")
                        .HasColumnType("REAL");

                    b.Property<double>("Vz")
                        .HasColumnType("REAL");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<double>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Stars");
                });
#pragma warning restore 612, 618
        }
    }
}
