//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Frank.Apps.BuildTool.Cli.Types
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
    public partial class Project
    {

        private PropertyGroupType[] propertyGroupField;

        private ItemGroupType[] itemGroupField;

        private ItemDefinitionGroupType[] itemDefinitionGroupField;

        private ChooseType[] chooseField;

        private UsingTaskType[] usingTaskField;

        private System.Xml.XmlNode[] projectExtensionsField;

        private TargetType targetField;

        private ImportType importField;

        private ImportGroupType importGroupField;

        private PropertyGroupType[] propertyGroup1Field;

        private ItemGroupType[] itemGroup1Field;

        private ItemDefinitionGroupType[] itemDefinitionGroup1Field;

        private ChooseType[] choose1Field;

        private UsingTaskType[] usingTask1Field;

        private TargetType[] target1Field;

        private ImportType[] import1Field;

        private ImportGroupType[] importGroup1Field;

        private System.Xml.XmlNode[] projectExtensions1Field;

        private string defaultTargetsField;

        private string initialTargetsField;

        private string sdkField;

        private string toolsVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup", Order = 0)]
        public PropertyGroupType[] PropertyGroup
        {
            get { return this.propertyGroupField; }
            set { this.propertyGroupField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemGroup", Order = 1)]
        public ItemGroupType[] ItemGroup
        {
            get { return this.itemGroupField; }
            set { this.itemGroupField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemDefinitionGroup", Order = 2)]
        public ItemDefinitionGroupType[] ItemDefinitionGroup
        {
            get { return this.itemDefinitionGroupField; }
            set { this.itemDefinitionGroupField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Choose", Order = 3)]
        public ChooseType[] Choose
        {
            get { return this.chooseField; }
            set { this.chooseField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsingTask", Order = 4)]
        public UsingTaskType[] UsingTask
        {
            get { return this.usingTaskField; }
            set { this.usingTaskField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectExtensions", Order = 5)]
        public System.Xml.XmlNode[] ProjectExtensions
        {
            get { return this.projectExtensionsField; }
            set { this.projectExtensionsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public TargetType Target
        {
            get { return this.targetField; }
            set { this.targetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public ImportType Import
        {
            get { return this.importField; }
            set { this.importField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public ImportGroupType ImportGroup
        {
            get { return this.importGroupField; }
            set { this.importGroupField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup", Order = 9)]
        public PropertyGroupType[] PropertyGroup1
        {
            get { return this.propertyGroup1Field; }
            set { this.propertyGroup1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemGroup", Order = 10)]
        public ItemGroupType[] ItemGroup1
        {
            get { return this.itemGroup1Field; }
            set { this.itemGroup1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemDefinitionGroup", Order = 11)]
        public ItemDefinitionGroupType[] ItemDefinitionGroup1
        {
            get { return this.itemDefinitionGroup1Field; }
            set { this.itemDefinitionGroup1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Choose", Order = 12)]
        public ChooseType[] Choose1
        {
            get { return this.choose1Field; }
            set { this.choose1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsingTask", Order = 13)]
        public UsingTaskType[] UsingTask1
        {
            get { return this.usingTask1Field; }
            set { this.usingTask1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target", Order = 14)]
        public TargetType[] Target1
        {
            get { return this.target1Field; }
            set { this.target1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Import", Order = 15)]
        public ImportType[] Import1
        {
            get { return this.import1Field; }
            set { this.import1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImportGroup", Order = 16)]
        public ImportGroupType[] ImportGroup1
        {
            get { return this.importGroup1Field; }
            set { this.importGroup1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectExtensions", Order = 17)]
        public System.Xml.XmlNode[] ProjectExtensions1
        {
            get { return this.projectExtensions1Field; }
            set { this.projectExtensions1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultTargets
        {
            get { return this.defaultTargetsField; }
            set { this.defaultTargetsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InitialTargets
        {
            get { return this.initialTargetsField; }
            set { this.initialTargetsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sdk
        {
            get { return this.sdkField; }
            set { this.sdkField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToolsVersion
        {
            get { return this.toolsVersionField; }
            set { this.toolsVersionField = value; }
        }
    }
}
