# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  release:
    types: [prereleased]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  PreReleaseTestJob:
    runs-on: ubuntu-latest
    steps:
      - name: "Run only on prerelease"
